### PR TITLE
add pipeline_pixart_reference

### PR DESCRIPTION
**Pull request by eightmusic**
#I implemented an image-to-image pipeline, which can generate images according to the style of reference images.
import 
from io import BytesIO
import requests
import torch

# from diffusers import PixArtAlphaReferencePipeline
from scripts.reference_pipeline_inpaint import PixArtAlphaReferencePipeline

def download_image(url):
    response = requests.get(url)
    return PIL.Image.open(BytesIO(response.content)).convert("RGB")

# You can replace the checkpoint id with "PixArt-alpha/PixArt-XL-2-512x512" too.
pipe = PixArtAlphaReferencePipeline.from_pretrained("PixArt-alpha/PixArt-XL-2-1024-MS", torch_dtype=torch.float16)
pipe = [pipe.to](http://pipe.to/)('cuda')

img_url = "http://p1.qhimgs4.com/t01fef6f9d5e69335dd.jpg"
ref_image = download_image(img_url).crop((0, 0, 2160, 2160)).resize((1024, 1024))
image_out = pipe(
prompt = '',
height = 1024,
width = 1024,
image = ref_image,
num_inference_steps = 20,
guidance_scale = 4.0,
           ).images[0]
url_2
inpaint_url
The first image is the reference image, and the second image is the generated image
@lawrence-cj

### CODE REVIEW

**Comment by eightmusic** [comment]
Here are some other interesting results. The reference image is on the left and the generated image is on the right.
inpaint_1
inpaint_ok
inpaint_ok2_mirror
Prompt Adding words like 'same',' twins', 'mirror', and so on, may result in a higher success rate.

**Comment by lawrence-cj** [comment]
Thank you so much for your effort on this I2i task. It's super promising. Is it possible to generate images with text & reference conditioned together? Like the landmark reference image but generate objects? How about the result?

**Comment by eightmusic** [comment]
> Thank you so much for your effort on this I2i task. It's super promising. Is it possible to generate images with text & reference conditioned together? Like the landmark reference image but generate objects? How about the result?

I've tried generating text and reference-conditioned images simultaneously, but it seems like this might need further exploration, as sometimes it works and sometimes it doesn't.

**Comment by lawrence-cj** [comment]
Really great work.

**Pull request merged**
