### PR TITLE
Refractoring

### PR DESCRIPTION
**Pull request by SashaXser**

### CODE REVIEW

**Comment by lawrence-cj** [comment]
It's a huge change. The files in `diffusion/model/llava` and the files related to samplers are copied from other repos. Think we need to keep it unchagned. For the others will be merged after reviewed. WDYT @yujincheng08

**Comment by yujincheng08** [comment]
many of them are format changes. could u split into two commits so that we can better review?

**Comment by SashaXser** [comment]
> many of them are format changes. could u split into two commits so that we can better review?

Surely this makes sense? The main changes are: f-string, walrus, assign if expression, small format for ease of editing and Inline immediately returned variables.

**Comment by lawrence-cj** [comment]
OK, I'll do a review.

**Comment by lawrence-cj** [comment]
Thx so much for your effort.

**Pull request merged**
