### PR TITLE
add pipeline_pixart_inpaint

### PR DESCRIPTION
**Pull request by justbies**

### CODE REVIEW

**Comment by lawrence-cj** [comment]
Can we add a code block about how to use it?

**Comment by eightmusic** [comment]
> Can we add a code block about how to use it?
Here is an example of how to use it:
”“”
from scripts.pipeline_pixart_inpaint import PixArtAlphaInpaintPipeline

prompt = ""
image = Image.open('')
mask_image = Image.open('')
out = pipe(
            prompt,
            image=image,
            mask_image=mask_image,
            strength=1.0).images[0]
out.save('/path/to/save')
“”“

**Comment by lawrence-cj** [comment]
Is there any sample pairs (image, prompt, mas) to show the results?

**Comment by eightmusic** [comment]
kangaroo
kangaroo_inpaint_pix
kangaroo_mask_5
prompt=”“
The results above are the input image, the result, and the input mask.
An empty string is sufficient for prompt.

**Comment by eightmusic** [comment]
I just found a problem. I pull request with one account and commit with another.

**Comment by lawrence-cj** [comment]
How about the problem. Wondering any update :) @eightmusic

**Comment by eightmusic** [comment]
> How about the problem. Wondering any update :) @eightmusic

代码部分没有更新，就是pr用的一个账号，commit是另一个账号，我就是说一下，这里面的两个账号都是我的

**Comment by lawrence-cj** [comment]
Ok. Cool. Approved and merged. Thank you so much for your PR. 🥰

**Comment by eightmusic** [comment]
> Ok. Cool. Approved and merged. Thank you so much for your PR. 🥰

I also added this function in the diffuers official library, and the reviewer mentioned you. If you find it OK, could you please reply to him. @lawrence-cj

**Comment by lawrence-cj** [comment]
Got it. I'll look into it later.

**Comment by lavenderhhl** [comment]
Firstly, thank you for your PR.
But I had the following dimension error when running
image
I think we need to add the following code to do after line 972: 
image

**Comment by eightmusic** [comment]
There is no problem with the code you added. This has something to do with the diffusers version. I used version 0.24.0 to implement it. @lavenderhhl

**Comment by lavenderhhl** [comment]
> There is no problem with the code you added. This has something to do with the diffusers version. I used version 0.24.0 to implement it. @lavenderhhl

OK, I used diffusers==0.27.2 to implement it. Thank you!

**Pull request merged**
